/*====================================================
PROJECT : Superstore Sales SQL Analysis
AUTHOR  : Anshika Mishra
====================================================*/

USE superstore_analysis;
-- Query 1: Total Number of Orders
-- Business Question:
-- How many total orders are present in the dataset?
-- ==================================================
USE superstore_analysis;
SELECT COUNT(*) AS Total_Orders
FROM orders;
-- ==================================================
-- Query 2: Total Sales
-- Business Question:
-- What is the total sales generated by the company?
-- ==================================================
SELECT ROUND(SUM(SALES),2)AS Total_Sales
FROM orders;
-- ==================================================
-- Query 3: Total Profit
-- Business Question:
-- What is the total profit earned by the company?
-- ==================================================
SELECT ROUND(SUM(Profit),2)AS Total_Profit
FROM orders;
-- ==================================================
-- Query 4: Average Sales per Order
-- Business Question:
-- What is the average sales value per order?
-- ==================================================
USE superstore_analysis;
SELECT ROUND(AVG(Sales),2) AS Average_Sales
FROM orders;
-- ==================================================
-- Query 5: Total Quantity Sold
-- Business Question:
-- How many products were sold in total?
-- ==================================================
SELECT SUM(Quantity)AS Total_Quantity
FROM orders;
-- ==================================================
-- Query 6: Total Unique Customers
-- Business Question:
-- How many unique customers placed orders?
-- ==================================================
SELECT COUNT(DISTINCT 'Customer Name') AS Total_Customer
FROM orders;
-- ==================================================
-- Query 7: Total Categories
-- Business Question:
-- How many product categories are available?
-- ==================================================
SELECT COUNT(DISTINCT Category) AS Total_Categories
FROM orders;
-- ==================================================
-- Query 8: Sales by Category
-- Business Question:
-- Which product category generated the highest sales?
-- ==================================================

SELECT Category,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM orders
GROUP BY Category
ORDER BY Total_Sales DESC;
-- ==================================================
-- Query 9: Profit by Category
-- Business Question:
-- Which category generated the highest profit?
-- ==================================================

SELECT Category,
       ROUND(SUM(Profit),2) AS Total_Profit
FROM orders
GROUP BY Category
ORDER BY Total_Profit DESC;
-- ==================================================
-- Query 10: Top 10 Customers
-- Business Question:
-- Who are the top 10 customers based on sales?
-- ==================================================

SELECT `Customer Name`,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM orders
GROUP BY `Customer Name`
ORDER BY Total_Sales DESC
LIMIT 10;

-- ==================================================
-- Query 11: Sales by Region
-- Business Question:
-- Which region generated the highest sales?
-- ==================================================

SELECT Region,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM orders
GROUP BY Region
ORDER BY Total_Sales DESC;
-- ==================================================
-- Query 12: Profit by Region
-- Business Question:
-- Which region generated the highest profit?
-- ==================================================

SELECT Region,
       ROUND(SUM(Profit),2) AS Total_Profit
FROM orders
GROUP BY Region
ORDER BY Total_Profit DESC;
-- ==================================================
-- Query 13: Sales by State
-- Business Question:
-- Which states generated the highest sales?
-- ==================================================

SELECT State,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM orders
GROUP BY State
ORDER BY Total_Sales DESC
LIMIT 10;
-- ==================================================
-- Query 14: Top 10 Products
-- Business Question:
-- Which products generated the highest sales?
-- ==================================================

SELECT `Product Name`,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM orders
GROUP BY `Product Name`
ORDER BY Total_Sales DESC
LIMIT 10;
-- ==================================================
-- Query 15: Top 10 Cities
-- Business Question:
-- Which cities generated the highest sales?
-- ==================================================

SELECT City,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM orders
GROUP BY City
ORDER BY Total_Sales DESC
LIMIT 10;
-- ==================================================
-- Query 16: Profit by Category
-- Business Question:
-- Which category generated the highest profit?
-- ==================================================

SELECT Category,
       ROUND(SUM(Profit),2) AS Total_Profit
FROM orders
GROUP BY Category
ORDER BY Total_Profit DESC;
-- ==================================================
-- Query 17: Sales by Sub-Category
-- Business Question:
-- Which sub-category generated the highest sales?
-- ==================================================

SELECT `Sub-Category`,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM orders
GROUP BY `Sub-Category`
ORDER BY Total_Sales DESC;
-- ==================================================
-- Query 18: Average Profit by Category
-- Business Question:
-- What is the average profit for each category?
-- ==================================================

SELECT Category,
       ROUND(AVG(Profit),2) AS Average_Profit
FROM orders
GROUP BY Category
ORDER BY Average_Profit DESC;
-- ==================================================
-- Query 19: Top 10 Most Profitable Products
-- Business Question:
-- Which products generated the highest profit?
-- ==================================================

SELECT `Product Name`,
       ROUND(SUM(Profit),2) AS Total_Profit
FROM orders
GROUP BY `Product Name`
ORDER BY Total_Profit DESC
LIMIT 10;
-- ==================================================
-- Query 20: Least Profitable Products
-- Business Question:
-- Which products generated the lowest profit?
-- ==================================================

SELECT `Product Name`,
       ROUND(SUM(Profit),2) AS Total_Profit
FROM orders
GROUP BY `Product Name`
ORDER BY Total_Profit ASC
LIMIT 10;
-- ==================================================
-- Query 21: Monthly Sales Analysis
-- Business Question:
-- What is the total sales generated in each month?
-- ==================================================

SELECT MONTH(`Order Date`) AS Month,
       SUM(Sales) AS Total_Sales
FROM orders
GROUP BY MONTH(`Order Date`)
ORDER BY Month;
-- ==================================================
-- Query 22: Year-wise Sales Analysis
-- Business Question:
-- What is the total sales generated in each year?
-- ==================================================

SELECT YEAR(`Order Date`) AS Year,
       SUM(Sales) AS Total_Sales
FROM orders
GROUP BY YEAR(`Order Date`)
ORDER BY Year;
-- ==================================================
-- Query 23: Orders by Region
-- Business Question:
-- Which region received the highest number of orders?
-- ==================================================

SELECT Region,
       COUNT(*) AS Total_Orders
FROM orders
GROUP BY Region
ORDER BY Total_Orders DESC;
-- ==================================================
-- Query 24: Top 5 Customers by Profit
-- Business Question:
-- Which top 5 customers generated the highest profit?
-- ==================================================

SELECT `Customer Name`,
       SUM(Profit) AS Total_Profit
FROM orders
GROUP BY `Customer Name`
ORDER BY Total_Profit DESC
LIMIT 5;
-- ==================================================
-- Query 25: Average Discount by Category
-- Business Question:
-- What is the average discount offered in each product category?
-- ==================================================

SELECT Category,
       AVG(Discount) AS Average_Discount
FROM orders
GROUP BY Category
ORDER BY Average_Discount DESC;

-- ==================================================
-- Query 26: Sales by Customer Segment
-- Business Question:
-- Which customer segment generated the highest sales?
-- ==================================================

SELECT Segment,
       SUM(Sales) AS Total_Sales
FROM orders
GROUP BY Segment
ORDER BY Total_Sales DESC;


-- ==================================================
-- Query 27: Average Profit by Region
-- Business Question:
-- What is the average profit earned in each region?
-- ==================================================

SELECT Region,
       ROUND(AVG(Profit),2) AS Average_Profit
FROM orders
GROUP BY Region
ORDER BY Average_Profit DESC;


-- ==================================================
-- Query 28: Categories with Total Sales Greater Than 500000
-- Business Question:
-- Which product categories generated sales above 500000?
-- ==================================================

SELECT Category,
       SUM(Sales) AS Total_Sales
FROM orders
GROUP BY Category
HAVING SUM(Sales) > 500000;


-- ==================================================
-- Query 29: Profit Status using CASE
-- Business Question:
-- Is each order profitable or loss-making?
-- ==================================================

SELECT `Order ID`,
       Profit,
       CASE
           WHEN Profit > 0 THEN 'Profit'
           WHEN Profit < 0 THEN 'Loss'
           ELSE 'No Profit No Loss'
       END AS Profit_Status
FROM orders;


-- ==================================================
-- Query 30: Top 5 Highest Sales Orders
-- Business Question:
-- Which orders have the highest sales value?
-- ==================================================

SELECT `Order ID`,
       Sales
FROM orders
ORDER BY Sales DESC
LIMIT 5;


-- ==================================================
-- Query 31: Rank Customers by Sales
-- Business Question:
-- Rank customers based on total sales.
-- ==================================================

SELECT `Customer Name`,
       SUM(Sales) AS Total_Sales,
       RANK() OVER(ORDER BY SUM(Sales) DESC) AS Customer_Rank
FROM orders
GROUP BY `Customer Name`;


-- ==================================================
-- Query 32: Dense Rank Products by Profit
-- Business Question:
-- Rank products based on total profit.
-- ==================================================

SELECT `Product Name`,
       SUM(Profit) AS Total_Profit,
       DENSE_RANK() OVER(ORDER BY SUM(Profit) DESC) AS Product_Rank
FROM orders
GROUP BY `Product Name`;


-- ==================================================
-- Query 33: Running Total of Sales
-- Business Question:
-- What is the running total of sales?
-- ==================================================

SELECT `Order Date`,
       Sales,
       SUM(Sales) OVER(ORDER BY `Order Date`) AS Running_Total
FROM orders;


-- ==================================================
-- Query 34: Top Customer using Subquery
-- Business Question:
-- Which customer generated the highest sales?
-- ==================================================

SELECT *
FROM
(
    SELECT `Customer Name`,
           SUM(Sales) AS Total_Sales
    FROM orders
    GROUP BY `Customer Name`
) AS CustomerSales
ORDER BY Total_Sales DESC
LIMIT 1;
-- ==================================================
-- Query 35: Total Sales, Profit and Orders by Region
-- Business Question:
-- Show sales, profit and total orders for each region.
-- ==================================================

SELECT Region,
       COUNT(*) AS Total_Orders,
       SUM(Sales) AS Total_Sales,
       SUM(Profit) AS Total_Profit
FROM orders
GROUP BY Region
ORDER BY Total_Sales DESC;